backend:
  name: github
  repo: Meda111666/portfolio
  branch: main

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "blog"
    label: "Blogovi"
    folder: "src/blogs"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Naslov", widget: "string" }
      - { name: "date", label: "Datum", widget: "datetime" }
      - { name: "body", label: "Sadr≈æaj", widget: "markdown" }
